### ISSUE TITLE
Unable to run tests with mock on iOS

### ISSUE THREAD

**Issue by kartik-prakash** [kosi-libs/MocKMP#42]
I will shortly share a sample project on this, however when running tests for iOS in a multiplatform project, tests are passing for `android` but failing for `iOS` with the following error:

```
Uncaught Kotlin exception: org.kodein.mock.Mocker.MockingException: <My mocked class>.itsFunction() has not been mocked
Invalid connection: com.apple.coresymbolicationd
```

Anyone has seen that before or know how to resolve this?

**Comment by SalomonBrys** [comment]
How are you applying MocKMP ?
Can you share a reproducer ?

**Comment by kartik-prakash** [comment]
@SalomonBrys  Sorry for the delay, I was trying to figure out what's going on. So it seems like an issue with maybe scope in tests. Here is the setup:

```
interface Foo {
    fun doSomething(): Boolean
}

class Bar(private val foo: Foo) {
    suspend fun bar(): Boolean {
        return foo.doSomething()
    }
}

@UsesMocks(Foo::class)
class MyTest : TestsWithMocks() {
    override fun setUpMocks() {

    }

    private val myFoo: Foo = MockFoo(mocker)
    private val sut: Bar = Bar(myFoo)

    @BeforeTest
    fun setup() {
        every { myFoo.doSomething() } returns true
    }

    @Test
    fun `this is a test`() = runTest {
        val actual = sut.bar()
        assertTrue { actual }
    }
}
```

The above test passes for android but fails for iOS. I'm assuming it's something to do with `runTest{}`. But explicitly calling `setup()` inside the test passes:

```
@Test
    fun `this is a test`() = runTest {
        val actual = sut.bar()
        assertTrue { actual }
    }
```

**Comment by kartik-prakash** [comment]
Update: Moving everything I have above in `setup()` to `setupMocks()` from `TestsWithMocks` solved the issue.

**Comment by SalomonBrys** [comment]
This needs to be documented

**Comment by SalomonBrys** [comment]
The problem came from:

```kotlin
    override fun setUpMocks() {

    }
```

You're supposed to override `setUpMock` with the `injectMocks` method that was generated:

```kotlin
override fun setUpMocks() = injectMocks(mocker)
```
