### ISSUE TITLE
Call count for mocks

### ISSUE THREAD

**Issue by afonsograca** [kosi-libs/MocKMP#44]
Are there any plans to add the ability of verifying how many times an expectation was called? Sometimes a simple yes/no is not enough to track down some unexpected behaviour.
Keep up the great work. 🙌

**Comment by SalomonBrys** [comment]
Is this not sufficient?

```kotlin
verify {
    repeat(5) { myAmazingApi(isAny()) }
}
```

**Comment by SalomonBrys** [comment]
At the moment, we'll consider that using `repeat` is sufficient.
Feel free to reopen this issue with a use case if that is not enough.
