### ISSUE TITLE
Kotlin 1.8 support

### ISSUE THREAD

**Issue by jdamcd** [kosi-libs/MocKMP#46]
Plugin version 1.11.0 produces the following error in a project using Kotlin 1.8: 

```
Unable to find method ''void org.jetbrains.kotlin.gradle.tasks.KotlinCompile.<init>(org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions, org.gradle.workers.WorkerExecutor, org.gradle.api.model.ObjectFactory)''
'void org.jetbrains.kotlin.gradle.tasks.KotlinCompile.<init>(org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions, org.gradle.workers.WorkerExecutor, org.gradle.api.model.ObjectFactory)'
```

I checked out an old Kotlin 1.7.20 commit of the same project and everything looks good.

**Comment by SalomonBrys** [comment]
This issue is currently preventing us from supporting Kotlin 1.8: https://youtrack.jetbrains.com/issue/KT-55720/KJS-IR-ReferenceError-SuspendFunction1-is-not-defined-with-1.8
We are waiting on its resolution.

**Comment by SalomonBrys** [comment]
MocKMP 1.12.0 is compiled with Kotlin 1.8.
Note that you may need to add:
```kotlin
kotlin.incremental.js.ir=false
```
If you are mocking suspend functions in JS.
