### ISSUE TITLE
Provide a way to use something like TestsWithMocks for classes that already have a super class

### ISSUE THREAD

**Issue by dalewking** [kosi-libs/MocKMP#50]
My thought is that you could declare an interface for TestsWithMocks functionality and it could be mixed into the class using delegation. You could not do the @BeforeTest method that way so you would have to provide a method the test class can call from a BeforeTest method

**Comment by SalomonBrys** [comment]
Fix released in [v1.14.0](https://github.com/kosi-libs/MocKMP/releases/tag/v1.14.0).
