### ISSUE TITLE
Trying to run with older version of ksp does not work

### ISSUE THREAD

**Issue by dalewking** [kosi-libs/MocKMP#51]
Readme has this:

> If you are not using the same Kotlin version than the plugin, then you’ll need to manually apply the KSP plugin before applying MocKMP:
```
plugins {
    id("com.google.devtools.ksp") version "1.7.22-1.0.8"
    id("org.kodein.mock.mockmp") version "{version}"
}
```
However this does not work and I get:

ksp-1.8.0-1.0.8 is too new for kotlin-1.7.22. Please upgrade kotlin-gradle-plugin to 1.8.0.

**Comment by SalomonBrys** [comment]
The plugin can only work with the KSP version it was compiled with.
Unfortunately, you need to revert to manual configuration if you want to do something like this.
