### ISSUE TITLE
New feature to generate for CommonMain not generating code

### ISSUE THREAD

**Issue by dalewking** [kosi-libs/MocKMP#52]
The new feature #47 does not appear to be working in that while it applies the runtime dependencies, no mock classes are generated. No ksp task is ran nor is a ksp task showing up in tasks and no build/generated/ksp folder is created

I am using 1.12.0 with the workaround I posted in #51 to use ksp for 1.7.21

**Comment by dalewking** [comment]
I think basically you have to do the same workaround you do for common test with common main

**Comment by SalomonBrys** [comment]
Doing the same workaround would be very bad for every other KSP lib.
This feature is niche, so I am going to wait to see how KSP will properly support multiplatform.

**Comment by dalewking** [comment]
So I have this working for platform specific code without using your gradle plugin. So what I am doing is:

- Applying the ksp gradle plugin to the project
- Adding the runtime dependency to commonMain source set
- To specify arguments I am doing:
```
ksp {
    arg("org.kodein.mock.errors", "throw")
    arg("org.kodein.mock.visibility", "public")
}
```
- I add the processor like this:
```
dependencies {
    configurations
        .filter { "ksp" in it.name }
        .filter { "Android" in it.name || "Ios" in it.name }
        .filter { "Test" !in it.name }
        .forEach { it(libs.mockmp.processor) }
}
```

This actually works when you run it in gradle. The only issue is that in Android Studio the injectMocks call is showing as an error because that call is only part of the target, not the common code.

I am working around this using an expect/actual call to do the injection in each platform.

I think this could be resolved with some slight tweaks to MocKMP, borrowing an idea from Mockative. The idea would be to:
- Declare a function like this in the runtime library:
```
package org.kodein.mock

fun <T : Any> Mocker.injectMocks(instance: T) {
    // throw an exception because we only get here if there are no mocks for the given instance
}
```
- So for each class that you you generate a .injectMocks function for (e.g. Foo in this example) you also generate:
```
package org.kodein.mock

fun Mocker.injectMocks(instance: Foo) = instance.injectMocks(this)
```

So in your class you call `Mocker.injectMocks(this)`

This satisfies Android Studio because it will resolve to the one in the runtime. When compiling for a platform it will pick up the one that was generated.

**Comment by SalomonBrys** [comment]
MocKMP changes the way it is applied to project.
It is now easy to [apply to the main source sets](https://kosi-libs.org/mockmp/1.17/core/setup.html#_applying_to_main_source_sets).
