### ISSUE TITLE
kotlin-test related issue with TestWithMocks: @BeforeTest priority

### ISSUE THREAD

**Issue by glureau** [kosi-libs/MocKMP#55]
Due to this issue https://youtrack.jetbrains.com/issue/KT-54932, TestWithMocks can be unreliable on ios/macos.

It could be great to have either a better approach that don't rely on this @BeforeTest (maybe via class construction?), or at least a documentation stating the issue and the best workaround.

**Comment by SalomonBrys** [comment]
Fix released in [v1.14.0](https://github.com/kosi-libs/MocKMP/releases/tag/v1.14.0).
