### ISSUE TITLE
java.lang.RuntimeException: Could not find a way to get a reference of MySealedInterface

### ISSUE THREAD

**Issue by ankushg** [kosi-libs/MocKMP#56]
I'm running into issues with `sealed interface`s and `sealed class`es when attempting to match in a Mock with `isAny()`

The stacktrace is coming from `ArgConstraintsBuilder.toReturn`

which calls `References.getReference`
which calls `cls.isInstance(ref)` which seems eventually seems to throw an error for sealed interfaces from `validateProxyInterfaces`

I've worked around it for now by rewriting tests to just explicitly assert equality instead of using `isAny()`, but this should probably at least be documented 😅

**Comment by motorro** [comment]
@ankushg did you upgrade to AGP8 and Java17? 
I had my tests running but upgraded dependencies and it seems that matters. 
Haven't done proper git bisecting yet but I suspect the issue is there as I didn't change any sources

**Comment by motorro** [comment]
Confirmed. Reverting to:
- Gradle 7.5 from 8.0
- AGP 7.4.1 from 8.0
- Compile options, `sourceCompatibility` VERSION_17 to VERSION 1_8
- Kotlin options `jvmTarget` "17" to "1.8"
Fixes tests

**Comment by SalomonBrys** [comment]
Fix released in [v1.14.0](https://github.com/kosi-libs/MocKMP/releases/tag/v1.14.0).
