### ISSUE TITLE
Naming collision on generated fakes

### ISSUE THREAD

**Issue by afonsograca** [kosi-libs/MocKMP#57]
Hi there,

I'm using a library that contains a couple of classes like this:
```kotlin
data class Foo(...) {
   data class Data(...) 
}

data class Bar(...) {
   data class Data(...) 
}
```

When trying to write tests, I'd like to generate fakes based on those `Data` classes, and so I added
```
@UsesFakes(Foo.Data::class)
```
and 
```
@UsesFakes(Bar.Data::class)
```
to their respective cases.

Unfortunately I get a `kotlin.io.FileAlreadyExistsException` where `fakeData` already exists. Is there a way to give a custom name to the fake? something like
```
@UsesFakes(Foo.Data::class as FooData)
```

Cheers!

**Comment by SalomonBrys** [comment]
Fix released in [v1.14.0](https://github.com/kosi-libs/MocKMP/releases/tag/v1.14.0).
