### ISSUE TITLE
Would be nice if suspending function setup did not require you to be in suspend function

### ISSUE THREAD

**Issue by dalewking** [kosi-libs/MocKMP#60]
It would be nice if calls like registerSuspend, everySuspend, and verifyWithSuspend were not suspend functions. If you look at MockK for comparison its equivalents like coEvery and coVerify are not suspending functions and they just internally wrap the calls to the suspending block in a runBlocking.

**Comment by SalomonBrys** [comment]
That is on purpose.
We provide both `*Suspend` and `*` functions, to be used in both a suspending or a regular environment.
Using `runBlocking` might break test coroutines if their mocked implementation suspends.
