### ISSUE TITLE
1.14.0 has issue with kotlinx serialization

### ISSUE THREAD

**Issue by glureau** [kosi-libs/MocKMP#66]
1.14.0 is the latest Kotlin 1.8.X available version, but unfortunately it's loading kotlin 1.8.20 and this version [has issue](https://youtrack.jetbrains.com/issue/KT-57647/Serialization-IllegalAccessError-Update-to-static-final-field-caused-by-serializable-value-class?s=update-to-static-final-field-attempted-from-a-different-method-constructor-impl-than-the-initializer-method-clinit-when) with ktx serialization (1.8.21 fixes this issue).

As a workaround we can force the kotlin version in gradle, but maybe a 1.14.1 with Kotlin 1.8.21 would avoid this issue to other developers. (just a suggestion, feel free to close)

**Comment by SalomonBrys** [comment]
Version 1.16.0 is compiled with Kotlin 1.9.20 & KSP 1.0.14 :)
