### ISSUE TITLE
ksp-1.9.0-1.0.12 is too old for kotlin-1.9.10

### ISSUE THREAD

**Issue by FelixSubject211** [kosi-libs/MocKMP#70]
If I use MocKMP ich get "ksp-1.9.0-1.0.12 is too old for kotlin-1.9.10. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0." by build the Projekt. Is that a Problem?

**Comment by abhriyaroy** [comment]
Facing the same issue.

**Comment by SalomonBrys** [comment]
MocKMP 2.0 has been released and does not apply the KSP plugin anymore.
You are therefore free to apply the version you want ;)
