### ISSUE TITLE
Struggeling to add the library with version 1.16.0

### ISSUE THREAD

**Issue by HannahShulman** [kosi-libs/MocKMP#71]
I am looking to add this library, however, instructions arnt very clear.
When I use 1.15.0, I can sync the project, but cant override setUpMocks as described in the readme.

My plugins are: 
    kotlin("multiplatform") version "1.9.0"
    id("com.android.library")
    id("com.google.devtools.ksp") version "1.9.0-1.0.11"
    id("app.cash.sqldelight") version "2.0.0"
    kotlin("plugin.serialization") version "1.8.21"
    id("org.kodein.mock.mockmp") version "1.15.0"

Id appreciate any support, Thanks

**Comment by SalomonBrys** [comment]
This for issues, not help.
You can find help on the #kodein channel of the Kotlin Slack.
