### ISSUE TITLE
Suspension functions can be called only within coroutine body

### ISSUE THREAD

**Issue by Irfanulhaq1991** [kosi-libs/MocKMP#73]
Could execute every and verify on coroutine suspend methods

`      every { userRemoteDataSource.authenticate(isAny(),isAny()) } returns Result.success(UserRemoteDto("",200))
        usrRepo.authenticate("###","###")
        verify { userRemoteDataSource.authenticate(isAny(),isAny()) }`

**Comment by SalomonBrys** [comment]
Use:

- `everySuspend`: https://kosi-libs.org/mockmp/1.17/core/mocking.html#_defining_suspending_behaviour
- `verifyWithSuspend`: https://kosi-libs.org/mockmp/1.17/core/mocking.html#_verifying
