### ISSUE TITLE
Provide/Document way to create custom argument constraints

### ISSUE THREAD

**Issue by dalewking** [kosi-libs/MocKMP#74]
I see no documentation on how to create custom constraints and looking at the code it does not appear to actually be possible (e.g. ArgConstraint is not open). The constraints provided are very rudimentary and there are many possibilities missing e.g. greater than, less than, between, combining multiple constraints, constraints on properties of the object.

**Comment by SalomonBrys** [comment]
Use `isValid`.
It is documented in the section called "defining custom argument constraints" : https://kosi-libs.org/mockmp/1.17/core/mocking.html#_defining_custom_argument_constraints.
