### ISSUE TITLE
Issue when updating to kotlin 2.0

### ISSUE THREAD

**Issue by vijimani17** [kosi-libs/MocKMP#78]
We are using MocKMP for unit testing in our project, we are currently migrating to kotlin 2.0 , while doing it we are seeing below the issue

 C:\Users\vmanika\Trimbl\Instinct\chatCompanionApp\code\instinct-companion\composeApp\build\generated\ksp\android\androidUnitTestDebug\kotli
 n\com\trimble\ttm\kmp\companion\repo\MockMessageFirebaseRepo.kt', 'C:\Users\vmanika\Trimbl\Instinct\chatCompanionApp\code\instinct-com
 panion\composeApp\build\generated\ksp\android\androidUnitTestDebug\kotlin\com\trimble\ttm\kmp\companion\repo\MockTranslatorRepo.kt', '
 C:\Users\vmanika\Trimbl\Instinct\chatCompanionApp\code\instinct-companion\composeApp\build\generated\ksp\android\androidUnitTestDebug\
 kotlin\com\trimble\ttm\kmp\companion\repo\MockUserDetailsRepo.kt', 'C:\Users\vmanika\Trimbl\Instinct\chatCompanionApp\code\instinct-companio
 n\composeApp\build\generated\ksp\android\androidUnitTestDebug\kotlin\com\trimble\ttm\kmp\companion\usecase\MessageUseCaseTest_injectMocks.kt', 
 'C:\Users\vmanika\Trimbl\Instinct\chatCompanionApp\code\instinct-companion\composeApp\build\generated\ksp\andr
 oid\androidUnitTestDebug\kotlin\com\trimble\ttm\kmp\companion\usecase\MockILanguagePreferenceUseCase.kt'

 can be a part of only one module, but is listed as a source for both `androidUnitTestDebug` and `commonTest`, please check you -Xfragment-sources options.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':composeApp:compileDebugUnitTestKotlinAndroid'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
   
   
   
   " can be a part of only one module, but is listed as a source for both `androidUnitTestDebug` and `commonTest`, please check you -Xfragment-sources options."

I have code in only one module which is commonTest , But KSP is generating under "androidUnitTestDebug\kotlin\com\trimble\ttm\kmp\companion\" 

Does anyone faces the same issue  , is there any work around is there

**Comment by flipper09112** [comment]
Someone already got a workArround?

Im facing the same problem. I need run to android for get the coverage report.

**Comment by SalomonBrys** [comment]
Duplicates https://github.com/kosi-libs/MocKMP/issues/77
